/* Y Soft — primitivas visuales. Mantener estados y acciones explícitos. */
(function () {
  const D = window.YSoft = window.YSoft || {};
  const h = React.createElement;
  D.h = h;
  D.Icon = function Icon({ name, size = 18, stroke = 1.8 }) { return h('svg', { width:size, height:size, viewBox:'0 0 24 24', fill:'none', stroke:'currentColor', strokeWidth:stroke, strokeLinecap:'round', strokeLinejoin:'round', 'aria-hidden':true }, h('path', { d:D.icons[name] || D.icons.grid })); };
  D.Button = function Button({ children, kind='secondary', icon, onClick, disabled=false, type='button' }) { return h('button', { type, className:'button button-' + kind, onClick, disabled }, icon ? [h(D.Icon, { key:'icon', name:icon, size:16 }), h('span', { key:'label' }, children)] : children); };
  D.Status = function Status({ children, tone='green' }) { return h('span', { className:'status status-' + tone }, children); };
  D.Kpi = function Kpi({ label, value, note, primary, icon }) { return h('div', { className:'kpi-card' + (primary ? ' primary' : '') }, [h('div', { className:'kpi-topline' }, [icon && h('div', { key:'icon', className:'kpi-icon' }, h(D.Icon, { name:icon, size:21 })), h('div', { key:'label', className:'kpi-label' }, label)]), h('div', { className:'kpi-value' }, value), h('div', { className:'kpi-note' }, note)]); };
  D.Action = function Action({ icon, title, detail, onClick }) { return h('button', { className:'action-card', onClick }, [h('div', { key:'icon', className:'action-icon' }, h(D.Icon, { name:icon, size:21 })), h('div', { key:'copy' }, [h('strong', { key:'title' }, title), h('span', { key:'detail' }, detail)])]); };
  D.Ledger = function Ledger({ movements }) { return h('div', { className:'ledger' }, movements.map((movement) => h('div', { className:'ledger-row', key:movement.id }, [h('div', { className:'ledger-marker ' + movement.color }), h('div', { className:'ledger-main' }, [h('strong', null, movement.type), h('span', null, movement.detail + ' · ' + movement.time)]), h('div', { className:'ledger-amount' }, movement.amount > 0 ? '+ ' + D.money(movement.amount) : '− ' + D.money(Math.abs(movement.amount)))]))); };
  D.BottomNav = function BottomNav({ view, setView }) { const items=[['inicio','home','Inicio'],['ventas','rotate','Movimientos'],['menu','menu','Menú']]; return h('nav', { className:'bottom-nav', 'aria-label':'Navegación principal' }, h('div', { className:'bottom-nav-inner' }, items.map(([id,icon,label]) => h('button', { className:'nav-item primary-nav' + (view===id || (id === 'ventas' && ['ventas','caja','clientes'].includes(view)) ? ' active' : ''), key:id, onClick:()=>setView(id) }, [h(D.Icon, { key:'icon', name:icon, size:22 }), h('span', { key:'label' }, label)])))); };
})();
